### ISSUE TITLE
Missing info about runnig

### ISSUE THREAD

**Issue by Miso-K** [canoalberto/Kappa-Updated-Ensemble#2]
Hello,

Readme does not contain info about how to run this model.
Simply running ./run.sh doesn't work.
Also please add info how to run with MOA GUI.

**Comment by canoalberto** [comment]
To use the example ./run.sh the code must be built first using the pom file and maven. Simply run "mvn package" to generate the necessary jar files on the "target" folder.

To use it within the MOA GUI you must load the MOA GUI class "moa.gui.GUI" and add the KUE jar to the classpath.

**Comment by Miso-K** [comment]
Thank you!
